version: '3.5'
services:

    keycloak:
        container_name: keycloak
        image: jboss/keycloak:13.0.0
        restart: always
        volumes:
            - "./realm-export.json:/tmp/realm-export.json"
        ports:
            - "8080:8080"
        environment:
            KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
            KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
            DB_VENDOR: H2
            KEYCLOAK_IMPORT: /tmp/realm-export.json
            KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth

    # frontend:
    #     container_name: frontend
    #     #image: 409255/frontend
    #     build:
    #         context: .
    #     volumes:
    #         - "./nginx.conf:/etc/nginx/nginx.conf"
    #     ports:
    #         - "80:80"
    #     depends_on:
    #         - keycloak
    #         - backend

    backend:
        container_name: backend
        #image: 409255/backend
        image: chat-service
        ports:
            - "9012:9012"
        env_file:
            - backend.env
        depends_on:
            - keycloak
            - chat-db

    chat-db:
        container_name: chat-db
        image: mysql
        #volumes:
        #    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
    
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 9090:8080
        depends_on:
            - chat-db