version: '3.5'
services:

  keycloak:
    image: jboss/keycloak:13.0.0
    restart: always
    volumes:
        - "./realm-export.json:/tmp/realm-export.json"
    ports:
        - "8180:8080"
    environment:
        KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
        DB_VENDOR: H2
        KEYCLOAK_IMPORT: /tmp/realm-export.json